[package]
name = "aurora-cli-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora-engine-transactions = { git = "https://github.com/aurora-is-near/aurora-engine", rev = "96263de9ca3906c2dd014a2357a2aa68a1431731", features = ["std"] }
hex = "0.4.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
