[package]
name = "aurora-cli-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora-engine = { path = "./aurora-engine/engine/", features = ["std"] }
aurora-engine-sdk = { path = "./aurora-engine/engine-sdk/", features = ["std"] }
aurora-engine-transactions = { path = "./aurora-engine/engine-transactions/", features = ["std"] }
aurora-engine-types = { path = "./aurora-engine/engine-types/", features = ["std"] }
base64 = "0.13.0"
borsh = "0.8.2"
clap = { version = "3.1.6", features = ["derive"] }
hex = "0.4.3"
libsecp256k1 = "0.3.5"
near-jsonrpc-client = { git = "https://github.com/near/near-jsonrpc-client-rs/", rev = "c8bed6aef58a6ac8aae6c02ca52e01213918037d" }
near-jsonrpc-primitives = "0.12.0"
near-primitives = "0.12.0"
reqwest = { version = "0.11", features = ["json"] }
rlp = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
