[package]
name = "aurora-cli-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora-engine = { git = "https://github.com/aurora-is-near/aurora-engine.git", tag = "2.7.0", features = ["std"] }
aurora-engine-precompiles = { git = "https://github.com/aurora-is-near/aurora-engine.git", tag = "2.7.0", features = ["std"] }
aurora-engine-sdk = { git = "https://github.com/aurora-is-near/aurora-engine.git", tag = "2.7.0", features = ["std"] }
aurora-engine-transactions = { git = "https://github.com/aurora-is-near/aurora-engine.git", tag = "2.7.0", features = ["std"] }
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", tag = "2.7.0", features = ["std"] }
base64 = "0.13.0"
borsh = "0.9.3"
bs58 = "0.4.0"
clap = { version = "3.1.6", features = ["derive"] }
ethabi = "17.1"
hex = "0.4.3"
libsecp256k1 = "0.3.5"
near-crypto = "0.12.0"
near-jsonrpc-client = { git = "https://github.com/near/near-jsonrpc-client-rs/", rev = "c8bed6aef58a6ac8aae6c02ca52e01213918037d" }
near-jsonrpc-primitives = "0.12.0"
near-primitives = "0.12.0"
reqwest = { version = "0.11", features = ["json"] }
rlp = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
